-- Drop tables if they exist to allow clean recreation
DROP TABLE IF EXISTS recomendaciones CASCADE;
DROP TABLE IF EXISTS analisis_matematico CASCADE;
DROP TABLE IF EXISTS historial_precios CASCADE;
DROP TABLE IF EXISTS tiendas CASCADE;
DROP TABLE IF EXISTS productos CASCADE;

-- 1. productos
CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    marca TEXT,
    categoria TEXT,
    search_term TEXT,
    url_knasta TEXT,
    fuente TEXT DEFAULT 'Knasta',
    fecha_creacion TIMESTAMP DEFAULT NOW(),
    fecha_actualizacion TIMESTAMP DEFAULT NOW()
);

-- 2. tiendas
CREATE TABLE tiendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    url_tienda TEXT,
    fecha_creacion TIMESTAMP DEFAULT NOW()
);

-- 3. historial_precios
CREATE TABLE historial_precios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
    tienda_id BIGINT REFERENCES tiendas(id) ON DELETE CASCADE,
    precio_actual INTEGER NOT NULL,
    precio_normal INTEGER,
    descuento INTEGER DEFAULT 0,
    disponible BOOLEAN DEFAULT true,
    fecha_registro DATE NOT NULL,
    fuente TEXT DEFAULT 'Knasta',
    fecha_creacion TIMESTAMP DEFAULT NOW(),
    -- Ensure we don't have duplicate records for the same product and store on the same day
    UNIQUE (producto_id, tienda_id, fecha_registro)
);

-- 4. analisis_matematico
CREATE TABLE analisis_matematico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
    tienda_id BIGINT REFERENCES tiendas(id) ON DELETE CASCADE,
    funcion_precio TEXT,
    pendiente_m NUMERIC,
    intercepto_b NUMERIC,
    derivada_aproximada NUMERIC,
    precio_promedio NUMERIC,
    limite_estimado NUMERIC,
    precio_proyectado NUMERIC,
    proyeccion_7d JSONB,
    confianza_proyeccion NUMERIC,
    factores_externos JSONB,
    puntaje NUMERIC,
    tendencia TEXT,
    fecha_analisis TIMESTAMP DEFAULT NOW()
);

-- 5. recomendaciones
CREATE TABLE recomendaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
    tienda_recomendada_id BIGINT REFERENCES tiendas(id),
    decision TEXT,
    descripcion TEXT,
    puntaje_final NUMERIC,
    fecha_recomendacion TIMESTAMP DEFAULT NOW()
);
